### ISSUE TITLE
Using two instances at the same time twrow NoClassDefFoundError

### ISSUE THREAD

**Issue by ClementGre** [prat-man/unique4j#11]
Hi,
I am trying to use Unique4J for a desktop app. I want to use only one instance only when the user is opening a file from the system file explorer. Otherwise, I want the user to be able to open as much instances as he wants.
I also wants that if the user starts a second instance that is not due to opening files, this new instance must grant the lock (send a message to the old instance so it can freeLock(), and then the new instance can acquireLock()), as described below:

When the user open the app to open a file (from the file explorer)
- If no instance already exists: open the app normally.
- If there is already an instance: close the current instance and send a message to the first instance.

When the user opens the app normally
- If no instance already exists: open the app normally.
- If there is already an instance: send a message to the first instance so it can freeLock(), and then the new instance can acquireLock().

The issue is that when the old instance free lock, the JVM is not anymore able to load classes, and throws NoClassDefFoundError when the app tries to load a class that have never been initialized before.

I have not this issue if the new instance does not ask to freeLock() (if the first instance keeps the lock, and the new one stays unlocked).

I do not know if this is a bug, or if it is normal, but I think that if the freeLock() method exists, it should work like this, I dont know.

Anyway, I know this is a detail, and it can also work without transferring the lock between my instances, but I think that if the user opens files, its files should opens on the last instance, and not the first one.
There is also an issue if the user closes the locked instance first, there will be only a non-locked instance, and the files will open on a new instance, but I don't think Unique4J is able to do this.

Thant you very much,
Clément Grennerat

**Comment by prat-man** [comment]
Hi,
Thank you for your interest in the Unique4j library.
Could you please provide me an example of the code as it will help me to debug the issue?
It would be helpful if you can include at which point the NoClassDefFoundError is thrown.
Thanks!

**Comment by ClementGre** [comment]
Hi,
I can give you the code I am working on: https://github.com/ClementGre/PDF4Teachers/blob/master/src/main/java/fr/clementgre/pdf4teachers/utils/AppInstancesManager.java
(regusterInstance() is called when main() is called).
(I am using JavaFX)

I will try to provide you a smaller example.

The NoClassDefFoundError is thrown after the lock have been free, when I try to use features of the app that I have never used before.

I will try to provide you a stack trace.

Thank you,
Clément G.

**Comment by prat-man** [comment]
Thank you for the code example.

I experimented with the scenario, and this seems to work for me.
However, you might be using the same strategy which is a bit strange.

```java
Unique4j unique = new Unique4jList(APP_ID, false) {
    @Override
    protected List<String> sendMessageList() {
        // send messages
        return null;
    }

    @Override
    protected void receiveMessageList(List<String> message) {
        if (condition) { // implement condition here
            try {
                // release lock on first instance
                this.freeLock();
            } catch (Unique4jException e) {
                e.printStackTrace();
            }
        }
    }
};

// try to acquire lock
boolean lockAcquired = unique.acquireLock();

// failed to acquire lock, first instance had lock
// therefore, now first instance has released lock
// try to acquire lock again
if (!lockAcquired) {
    lockAcquired = unique.acquireLock();
}

// do long running tasks (start UI, etc.)

// application about to exit, try to free the lock
unique.freeLock();
```

**Comment by prat-man** [comment]
Here is a more detailed example of the strategy explained before.

```java
@Test
public void test() throws Unique4jException {
    Unique4j unique1 = initializeUnique4j(1);
    Unique4j unique2 = initializeUnique4j(2);
    Unique4j unique3 = initializeUnique4j(3);
    
    unique3.freeLock();
}

public Unique4j initializeUnique4j(final int index) throws Unique4jException {
    
    Unique4j unique = new Unique4jList(APP_ID, false) {
        @Override
        protected List<String> sendMessageList() {
            // send messages
            return null;
        }

        @Override
        protected void receiveMessageList(List<String> message) {
            // implement condition here
            try {
                // release lock on first instance
                this.freeLock();
                System.out.println("Instance " + index + " has released lock");
            } catch (Unique4jException e) {
                e.printStackTrace();
            }
        }
    };
    
    // try to acquire lock
    System.out.println("Instance " + index + " is trying to acquire lock");
    boolean lockAcquired = unique.acquireLock();
    
    // failed to acquire lock, first instance had lock
    // therefore, now first instance has released lock
    // try to acquire lock again
    if (!lockAcquired) {
        lockAcquired = unique.acquireLock();
    }
    
    if (lockAcquired) {
        System.out.println("Instance " + index + " has acquired lock");
    }
    else {
        System.out.println("Instance " + index + " has failed to acquire lock");
    }
    
    return unique;
}
```

Output:
```java
Instance 1 is trying to acquire lock
Instance 1 has acquired lock
Instance 2 is trying to acquire lock
Instance 1 has released lock
Instance 2 has acquired lock
Instance 3 is trying to acquire lock
Instance 2 has released lock
Instance 3 has acquired lock
```

**Comment by ClementGre** [comment]
Hi,

I am very sorry, but I just realized that this issue is due to IntelliJ IDEA that is running my two instances on the same Gradle Deamon. I am not sure of this, but I think it is the cause of this issue, because I can reproduce the error only when I run first from IntelliJ and then from the gradle task list.

But now, I can run my program perfectly. Transferring the lock works well.

Thank you for the work you've done on this library, and sorry again.
\- Clément

**Comment by prat-man** [comment]
I am glad your issue is resolved.
And once again thank you for your interest in my library.
Cheers! 😃
